"""Meeting agenda storage — persists the agent-generated + PM-edited agenda."""

import uuid
from datetime import datetime
from sqlalchemy import String, Integer, Text, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base, IdMixin, TimestampMixin


class MeetingAgenda(Base, IdMixin, TimestampMixin):
    """Stores the latest meeting agenda per project. Generated by the chat
    agent, editable by the PM in the Meeting Prep tab's markdown editor."""
    __tablename__ = "meeting_agendas"

    project_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("projects.id"), nullable=False)
    content_md: Mapped[str] = mapped_column(Text, nullable=False)
    generated_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    round_number: Mapped[int] = mapped_column(Integer, default=1)
    edited_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
