// [PAGE_NAME]Page.ts
// Generated by: qa-automation-agent
// Story: [JIRA_STORY_ID]
// Date: [GENERATION_DATE]

import { Page, Locator } from '@playwright/test';

/**
 * Page Object Model for [PAGE_NAME]
 *
 * Encapsulates page elements and interactions for [PAGE_DESCRIPTION]
 *
 * URL: [PAGE_URL]
 * Route: [PAGE_ROUTE]
 */
export class [PAGE_NAME]Page {
  readonly page: Page;

  // --- LOCATORS ---
  // Using self-healing selector hierarchy: Role → TestId → Text → CSS

  // Primary Actions
  readonly [primaryButton]: Locator;
  readonly [secondaryButton]: Locator;
  readonly [cancelButton]: Locator;

  // Form Elements
  readonly [inputField1]: Locator;
  readonly [inputField2]: Locator;
  readonly [dropdownSelect]: Locator;
  readonly [checkbox]: Locator;
  readonly [radioButton]: Locator;

  // Navigation Elements
  readonly [navLink1]: Locator;
  readonly [navLink2]: Locator;
  readonly [breadcrumb]: Locator;

  // Content Elements
  readonly [pageTitle]: Locator;
  readonly [mainContent]: Locator;
  readonly [dataTable]: Locator;
  readonly [tableRow]: Locator;

  // Messages & Notifications
  readonly [successMessage]: Locator;
  readonly [errorMessage]: Locator;
  readonly [warningMessage]: Locator;
  readonly [loadingSpinner]: Locator;

  /**
   * Constructor - Initialize page and locators
   */
  constructor(page: Page) {
    this.page = page;

    // Initialize locators using self-healing hierarchy
    // Priority 1: Semantic role (most stable)
    this.[primaryButton] = page.getByRole('button', { name: '[BUTTON_TEXT]' });

    // Priority 2: Test ID (requires data-testid attribute)
    this.[secondaryButton] = page.getByTestId('[BUTTON_TEST_ID]');

    // Priority 3: Text content
    this.[cancelButton] = page.getByText('[CANCEL_TEXT]');

    // Priority 4: CSS selector (fallback only)
    // this.[lastResortElement] = page.locator('[CSS_SELECTOR]');

    // Form field locators
    this.[inputField1] = page.getByLabel('[FIELD_LABEL_1]');
    this.[inputField2] = page.getByPlaceholder('[PLACEHOLDER_TEXT]');
    this.[dropdownSelect] = page.getByRole('combobox', { name: '[SELECT_LABEL]' });
    this.[checkbox] = page.getByRole('checkbox', { name: '[CHECKBOX_LABEL]' });

    // Navigation locators
    this.[navLink1] = page.getByRole('link', { name: '[LINK_TEXT_1]' });

    // Content locators
    this.[pageTitle] = page.getByRole('heading', { name: '[PAGE_TITLE]' });
    this.[dataTable] = page.getByRole('table');
    this.[tableRow] = page.getByRole('row');

    // Message locators
    this.[successMessage] = page.getByRole('alert').filter({ hasText: /success|completed/i });
    this.[errorMessage] = page.getByRole('alert').filter({ hasText: /error|failed/i });
    this.[loadingSpinner] = page.getByTestId('loading-spinner');
  }

  /**
   * Navigate to this page
   */
  async goto() {
    await this.page.goto('[PAGE_URL]');
    await this.waitForPageLoad();
  }

  /**
   * Wait for page to fully load
   * Override this method to customize loading detection
   */
  async waitForPageLoad() {
    // Wait for network to be idle
    await this.page.waitForLoadState('networkidle');

    // Wait for specific element that indicates page is ready
    await this.[pageTitle].waitFor({ state: 'visible' });

    // Wait for loading spinner to disappear (if present)
    if (await this.[loadingSpinner].isVisible({ timeout: 1000 }).catch(() => false)) {
      await this.[loadingSpinner].waitFor({ state: 'hidden' });
    }
  }

  // --- PRIMARY ACTIONS ---

  /**
   * [ACTION_DESCRIPTION_1]
   * @param [PARAM_NAME] - [PARAM_DESCRIPTION]
   */
  async [actionMethod1]([param]: string) {
    await this.[primaryButton].click();
    await this.waitForPageLoad();
  }

  /**
   * Fill form with provided data
   * @param formData - Object containing form field values
   */
  async fillForm(formData: {
    [field1]?: string;
    [field2]?: string;
    [selectOption]?: string;
    [checkboxValue]?: boolean;
  }) {
    // Fill text inputs
    if (formData.[field1]) {
      await this.[inputField1].fill(formData.[field1]);
    }

    if (formData.[field2]) {
      await this.[inputField2].fill(formData.[field2]);
    }

    // Select dropdown option
    if (formData.[selectOption]) {
      await this.[dropdownSelect].selectOption({ label: formData.[selectOption] });
    }

    // Handle checkbox
    if (formData.[checkboxValue] !== undefined) {
      if (formData.[checkboxValue]) {
        await this.[checkbox].check();
      } else {
        await this.[checkbox].uncheck();
      }
    }
  }

  /**
   * Submit the form
   * @param waitForNavigation - Whether to wait for page navigation after submit
   */
  async submitForm(waitForNavigation: boolean = true) {
    await this.[primaryButton].click();

    if (waitForNavigation) {
      await this.waitForPageLoad();
    }
  }

  /**
   * Cancel the current action
   */
  async cancel() {
    await this.[cancelButton].click();
    await this.waitForPageLoad();
  }

  // --- NAVIGATION ACTIONS ---

  /**
   * Navigate using page links
   * @param linkText - Text of the link to click
   */
  async navigateTo(linkText: string) {
    await this.page.getByRole('link', { name: linkText }).click();
    await this.waitForPageLoad();
  }

  // --- VERIFICATION METHODS ---

  /**
   * Check if success message is displayed
   * @returns true if success message visible
   */
  async isSuccessMessageVisible(): Promise<boolean> {
    return await this.[successMessage].isVisible({ timeout: 5000 }).catch(() => false);
  }

  /**
   * Get success message text
   * @returns Success message content
   */
  async getSuccessMessage(): Promise<string> {
    await this.[successMessage].waitFor({ state: 'visible' });
    return await this.[successMessage].textContent() || '';
  }

  /**
   * Check if error message is displayed
   * @returns true if error message visible
   */
  async isErrorMessageVisible(): Promise<boolean> {
    return await this.[errorMessage].isVisible({ timeout: 5000 }).catch(() => false);
  }

  /**
   * Get error message text
   * @returns Error message content
   */
  async getErrorMessage(): Promise<string> {
    await this.[errorMessage].waitFor({ state: 'visible' });
    return await this.[errorMessage].textContent() || '';
  }

  /**
   * Get page title
   * @returns Page title text
   */
  async getPageTitle(): Promise<string> {
    return await this.[pageTitle].textContent() || '';
  }

  /**
   * Check if element is enabled
   * @param locator - Element to check
   * @returns true if enabled
   */
  async isEnabled(locator: Locator): Promise<boolean> {
    return await locator.isEnabled();
  }

  /**
   * Check if page is in loading state
   * @returns true if loading spinner visible
   */
  async isLoading(): Promise<boolean> {
    return await this.[loadingSpinner].isVisible().catch(() => false);
  }

  // --- DATA TABLE INTERACTIONS ---

  /**
   * Get all rows from data table
   * @returns Array of row locators
   */
  async getTableRows(): Promise<Locator[]> {
    const rows = await this.[tableRow].all();
    return rows;
  }

  /**
   * Get specific table row by text content
   * @param text - Text to search for in row
   * @returns Row locator
   */
  async getTableRowByText(text: string): Promise<Locator> {
    return this.[tableRow].filter({ hasText: text });
  }

  /**
   * Click action button in specific table row
   * @param rowText - Row identifier text
   * @param buttonName - Button name/label
   */
  async clickRowAction(rowText: string, buttonName: string) {
    const row = await this.getTableRowByText(rowText);
    await row.getByRole('button', { name: buttonName }).click();
  }

  // --- FALLBACK STRATEGIES ---

  /**
   * Find element using fallback selector hierarchy
   * Tries multiple strategies to locate element
   *
   * @param options - Selector options in priority order
   * @returns Locator for the element
   */
  private async findElementWithFallback(options: {
    role?: { role: string; name: string };
    testId?: string;
    text?: string;
    css?: string;
  }): Promise<Locator> {
    // Try role-based selector (Priority 1)
    if (options.role) {
      const element = this.page.getByRole(options.role.role as any, { name: options.role.name });
      if (await element.isVisible({ timeout: 1000 }).catch(() => false)) {
        return element;
      }
    }

    // Try test ID (Priority 2)
    if (options.testId) {
      const element = this.page.getByTestId(options.testId);
      if (await element.isVisible({ timeout: 1000 }).catch(() => false)) {
        return element;
      }
    }

    // Try text content (Priority 3)
    if (options.text) {
      const element = this.page.getByText(options.text);
      if (await element.isVisible({ timeout: 1000 }).catch(() => false)) {
        return element;
      }
    }

    // CSS fallback (Priority 4 - least stable)
    if (options.css) {
      return this.page.locator(options.css);
    }

    throw new Error('Element not found with any fallback strategy');
  }

  // --- UTILITY METHODS ---

  /**
   * Take screenshot of current page state
   * @param name - Screenshot filename
   */
  async takeScreenshot(name: string) {
    await this.page.screenshot({ path: `screenshots/${name}.png`, fullPage: true });
  }

  /**
   * Wait for specific time (use sparingly, prefer auto-waiting)
   * @param ms - Milliseconds to wait
   */
  async wait(ms: number) {
    await this.page.waitForTimeout(ms);
  }

  /**
   * Get current URL
   * @returns Current page URL
   */
  async getCurrentUrl(): Promise<string> {
    return this.page.url();
  }

  /**
   * Verify page URL matches expected
   * @param expectedUrl - Expected URL or pattern
   */
  async expectUrl(expectedUrl: string | RegExp) {
    const currentUrl = await this.getCurrentUrl();

    if (typeof expectedUrl === 'string') {
      if (!currentUrl.includes(expectedUrl)) {
        throw new Error(`Expected URL to contain "${expectedUrl}", but got "${currentUrl}"`);
      }
    } else {
      if (!expectedUrl.test(currentUrl)) {
        throw new Error(`Expected URL to match ${expectedUrl}, but got "${currentUrl}"`);
      }
    }
  }
}

/**
 * USAGE EXAMPLE:
 *
 * import { [PAGE_NAME]Page } from '../pages/[PAGE_NAME]Page';
 *
 * test('Example test', async ({ page }) => {
 *   const [pageObject] = new [PAGE_NAME]Page(page);
 *
 *   await [pageObject].goto();
 *   await [pageObject].fillForm({
 *     [field1]: 'value1',
 *     [field2]: 'value2'
 *   });
 *   await [pageObject].submitForm();
 *
 *   expect(await [pageObject].isSuccessMessageVisible()).toBe(true);
 * });
 *
 * BEST PRACTICES:
 *
 * 1. Selector Strategy:
 *    - Always prefer getByRole() for semantic elements
 *    - Use getByTestId() for elements without semantic roles
 *    - Add data-testid attributes to frontend code
 *    - CSS selectors are last resort only
 *
 * 2. Locator Initialization:
 *    - Define all locators in constructor
 *    - Use readonly to prevent accidental reassignment
 *    - Group related locators together
 *
 * 3. Method Design:
 *    - Methods represent user actions (click, fill, navigate)
 *    - Return promises for async operations
 *    - Include JSDoc comments
 *    - Handle waits automatically
 *
 * 4. Maintainability:
 *    - Encapsulate page-specific logic
 *    - Keep tests clean and readable
 *    - Update selectors in one place
 *    - Use fallback strategies for robustness
 */
