// playwright.config.ts
// Generated by: qa-automation-agent
// Story: [JIRA_STORY_ID]
// Date: [GENERATION_DATE]

import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright Test Configuration
 *
 * Documentation: https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  // Test directory
  testDir: './tests',

  // Maximum time one test can run
  timeout: 30 * 1000, // 30 seconds

  // Maximum time for entire test suite
  globalTimeout: 60 * 60 * 1000, // 1 hour

  // Expect timeout for assertions
  expect: {
    timeout: 5000, // 5 seconds
  },

  // Run tests in files in parallel
  fullyParallel: true,

  // Fail the build on CI if you accidentally left test.only in the source code
  forbidOnly: !!process.env.CI,

  // Retry on CI only
  retries: process.env.CI ? 2 : 0,

  // Opt out of parallel tests on CI
  workers: process.env.CI ? 1 : undefined,

  // Reporter to use
  reporter: [
    // HTML reporter for local development
    ['html', { outputFolder: 'playwright-report', open: 'never' }],

    // List reporter for console output
    ['list'],

    // JSON reporter for CI/CD
    ['json', { outputFile: 'test-results/results.json' }],

    // JUnit reporter for CI integration
    ['junit', { outputFile: 'test-results/junit.xml' }],

    // ReportPortal integration (uncomment when configured)
    // ['@reportportal/agent-js-playwright', {
    //   apiKey: process.env.REPORTPORTAL_API_KEY,
    //   endpoint: process.env.REPORTPORTAL_ENDPOINT,
    //   project: process.env.REPORTPORTAL_PROJECT,
    //   launch: '[PROJECT_NAME] Test Run',
    //   description: 'Automated test execution for [JIRA_STORY_ID]',
    //   attributes: [
    //     { key: 'story', value: '[JIRA_STORY_ID]' },
    //     { key: 'environment', value: process.env.TEST_ENV || 'staging' },
    //   ],
    // }],
  ],

  // Shared settings for all projects
  use: {
    // Base URL for page.goto()
    baseURL: process.env.BASE_URL || '[DEFAULT_BASE_URL]',

    // Collect trace when retrying the failed test
    trace: 'on-first-retry',

    // Screenshot on failure
    screenshot: 'only-on-failure',

    // Video on failure
    video: 'retain-on-failure',

    // Maximum time each action (click, fill, etc.) can take
    actionTimeout: 10 * 1000, // 10 seconds

    // Navigation timeout
    navigationTimeout: 15 * 1000, // 15 seconds
  },

  // Configure projects for major browsers
  projects: [
    // --- DESKTOP BROWSERS ---

    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        // Browser-specific settings
        viewport: { width: 1920, height: 1080 },
        launchOptions: {
          args: [
            '--disable-web-security', // For local development only
            '--disable-features=IsolateOrigins,site-per-process'
          ],
        },
      },
    },

    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
        viewport: { width: 1920, height: 1080 },
      },
    },

    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
        viewport: { width: 1920, height: 1080 },
      },
    },

    // --- MOBILE BROWSERS ---

    {
      name: 'Mobile Chrome',
      use: {
        ...devices['Pixel 5'],
      },
    },

    {
      name: 'Mobile Safari',
      use: {
        ...devices['iPhone 13'],
      },
    },

    // --- TABLET BROWSERS ---

    {
      name: 'iPad',
      use: {
        ...devices['iPad Pro'],
      },
    },

    // --- BRANDED BROWSERS (Optional) ---

    // {
    //   name: 'Microsoft Edge',
    //   use: {
    //     ...devices['Desktop Edge'],
    //     channel: 'msedge',
    //   },
    // },

    // {
    //   name: 'Google Chrome',
    //   use: {
    //     ...devices['Desktop Chrome'],
    //     channel: 'chrome',
    //   },
    // },
  ],

  // Run your local dev server before starting the tests
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://localhost:3000',
  //   reuseExistingServer: !process.env.CI,
  //   timeout: 120 * 1000, // 2 minutes
  // },

  // Folder for test artifacts
  outputDir: 'test-results',

  // Preserve output across test runs
  preserveOutput: 'always',

  // Global setup/teardown
  // globalSetup: require.resolve('./global-setup'),
  // globalTeardown: require.resolve('./global-teardown'),
});

/**
 * ENVIRONMENT VARIABLES:
 *
 * Required:
 * - BASE_URL: Base URL for the application under test
 *   Example: BASE_URL=https://staging.example.com npm run test
 *
 * Optional:
 * - CI: Set to 'true' when running in CI/CD pipeline
 * - TEST_ENV: Environment name (dev, staging, prod)
 * - REPORTPORTAL_API_KEY: ReportPortal API key
 * - REPORTPORTAL_ENDPOINT: ReportPortal server URL
 * - REPORTPORTAL_PROJECT: ReportPortal project name
 *
 * USAGE EXAMPLES:
 *
 * Run all tests:
 *   npx playwright test
 *
 * Run tests in specific browser:
 *   npx playwright test --project=chromium
 *
 * Run specific test file:
 *   npx playwright test tests/login.spec.ts
 *
 * Run tests in headed mode:
 *   npx playwright test --headed
 *
 * Run tests in debug mode:
 *   npx playwright test --debug
 *
 * Run tests with specific tag:
 *   npx playwright test --grep @smoke
 *
 * Run tests excluding specific tag:
 *   npx playwright test --grep-invert @slow
 *
 * Run tests in parallel:
 *   npx playwright test --workers=4
 *
 * Run tests and open HTML report:
 *   npx playwright test && npx playwright show-report
 *
 * CI/CD INTEGRATION:
 *
 * GitHub Actions:
 *   - name: Run Playwright tests
 *     run: |
 *       npx playwright install --with-deps
 *       BASE_URL=${{ secrets.STAGING_URL }} npm run test:ci
 *
 * Jenkins:
 *   sh 'npx playwright install --with-deps'
 *   sh 'BASE_URL=${STAGING_URL} npm run test:ci'
 *
 * GitLab CI:
 *   script:
 *     - npx playwright install --with-deps
 *     - BASE_URL=$STAGING_URL npm run test:ci
 *
 * PERFORMANCE TUNING:
 *
 * 1. Parallel Execution:
 *    - workers: number of parallel workers
 *    - fullyParallel: true = run all tests in parallel
 *
 * 2. Timeouts:
 *    - timeout: max time per test
 *    - actionTimeout: max time per action
 *    - navigationTimeout: max time for navigation
 *
 * 3. Retries:
 *    - retries: 2 = retry failed tests twice
 *    - Only enable on CI to catch flaky tests
 *
 * 4. Test Artifacts:
 *    - trace: 'on-first-retry' = only on failures
 *    - screenshot: 'only-on-failure'
 *    - video: 'retain-on-failure'
 *
 * BEST PRACTICES:
 *
 * 1. Browser Selection:
 *    - Always test on Chromium (most common)
 *    - Add Firefox and WebKit for cross-browser coverage
 *    - Mobile testing for responsive features
 *
 * 2. Timeouts:
 *    - Set realistic timeouts for your app
 *    - Longer timeouts for slow operations (API calls, file uploads)
 *    - Shorter for fast operations (button clicks)
 *
 * 3. Reporters:
 *    - HTML for local debugging
 *    - JSON/JUnit for CI/CD integration
 *    - ReportPortal for centralized analytics
 *
 * 4. CI/CD:
 *    - Use forbidOnly to prevent test.only in production
 *    - Enable retries to handle flaky tests
 *    - Reduce workers on CI to avoid resource exhaustion
 *
 * 5. Environment Management:
 *    - Use environment variables for config
 *    - Different configs for dev/staging/prod
 *    - Never commit credentials
 */
