// test-fixtures.ts
// Generated by: qa-automation-agent
// Story: [JIRA_STORY_ID]
// Date: [GENERATION_DATE]

import { test as base, expect } from '@playwright/test';
import { [PAGE_OBJECT_NAME_1] } from './pages/[PAGE_OBJECT_NAME_1]';
import { [PAGE_OBJECT_NAME_2] } from './pages/[PAGE_OBJECT_NAME_2]';

/**
 * Custom Test Fixtures
 *
 * Extends Playwright's base test with custom fixtures for:
 * - Authenticated user sessions
 * - Page objects with automatic setup
 * - Test data fixtures
 * - API clients
 */

// Define custom fixture types
type CustomFixtures = {
  // Authenticated user context
  authenticatedPage: Page;
  authenticatedContext: BrowserContext;

  // Page Object fixtures
  [pageObject1]: [PAGE_OBJECT_NAME_1];
  [pageObject2]: [PAGE_OBJECT_NAME_2];

  // Test data fixtures
  testUser: {
    email: string;
    password: string;
    name: string;
  };

  testProduct: {
    id: string;
    name: string;
    price: number;
  };

  // API client fixture
  apiClient: {
    get: (endpoint: string) => Promise<any>;
    post: (endpoint: string, data: any) => Promise<any>;
    delete: (endpoint: string) => Promise<any>;
  };
};

/**
 * Extended test with custom fixtures
 *
 * Usage:
 * import { test, expect } from './test-fixtures';
 *
 * test('My test', async ({ [pageObject1], testUser }) => {
 *   // Fixtures are automatically set up and torn down
 * });
 */
export const test = base.extend<CustomFixtures>({
  // --- AUTHENTICATED PAGE FIXTURE ---
  authenticatedPage: async ({ browser }, use) => {
    // Create new context with authentication
    const context = await browser.newContext({
      storageState: {
        cookies: [
          {
            name: '[AUTH_COOKIE_NAME]',
            value: '[AUTH_TOKEN]',
            domain: '[DOMAIN]',
            path: '/',
            expires: Date.now() / 1000 + 3600, // 1 hour
            httpOnly: true,
            secure: true,
            sameSite: 'Lax',
          },
        ],
        origins: [],
      },
    });

    const page = await context.newPage();

    // Optionally: Verify authentication
    await page.goto('[BASE_URL]/[AUTHENTICATED_ROUTE]');
    await expect(page.getByTestId('user-menu')).toBeVisible();

    // Provide authenticated page to test
    await use(page);

    // Cleanup
    await page.close();
    await context.close();
  },

  // --- AUTHENTICATED CONTEXT FIXTURE ---
  authenticatedContext: async ({ browser }, use) => {
    // Load saved authentication state
    const context = await browser.newContext({
      storageState: 'auth-state.json', // Saved from login flow
    });

    await use(context);
    await context.close();
  },

  // --- PAGE OBJECT FIXTURES ---
  [pageObject1]: async ({ page }, use) => {
    const [pageObjectVar] = new [PAGE_OBJECT_NAME_1](page);

    // Optional: Navigate to page automatically
    await [pageObjectVar].goto();

    await use([pageObjectVar]);
    // Cleanup happens automatically
  },

  [pageObject2]: async ({ page }, use) => {
    const [pageObjectVar] = new [PAGE_OBJECT_NAME_2](page);
    await use([pageObjectVar]);
  },

  // --- TEST DATA FIXTURES ---
  testUser: async ({}, use) => {
    // Generate or load test user data
    const user = {
      email: `test.user.${Date.now()}@example.com`,
      password: '[TEST_PASSWORD]',
      name: 'Test User',
    };

    // Optionally: Create user via API
    // await createUserViaAPI(user);

    await use(user);

    // Cleanup: Delete test user
    // await deleteUserViaAPI(user.email);
  },

  testProduct: async ({}, use) => {
    const product = {
      id: `PROD-${Date.now()}`,
      name: 'Test Product',
      price: 99.99,
    };

    // Optionally: Create product via API
    // await createProductViaAPI(product);

    await use(product);

    // Cleanup: Delete product
    // await deleteProductViaAPI(product.id);
  },

  // --- API CLIENT FIXTURE ---
  apiClient: async ({ request }, use) => {
    const baseURL = process.env.API_BASE_URL || '[API_BASE_URL]';
    const apiKey = process.env.API_KEY || '[API_KEY]';

    const client = {
      async get(endpoint: string) {
        const response = await request.get(`${baseURL}${endpoint}`, {
          headers: {
            'Authorization': `Bearer ${apiKey}`,
            'Content-Type': 'application/json',
          },
        });
        return await response.json();
      },

      async post(endpoint: string, data: any) {
        const response = await request.post(`${baseURL}${endpoint}`, {
          headers: {
            'Authorization': `Bearer ${apiKey}`,
            'Content-Type': 'application/json',
          },
          data: data,
        });
        return await response.json();
      },

      async delete(endpoint: string) {
        const response = await request.delete(`${baseURL}${endpoint}`, {
          headers: {
            'Authorization': `Bearer ${apiKey}`,
          },
        });
        return response.ok;
      },
    };

    await use(client);
  },
});

export { expect };

/**
 * ADVANCED FIXTURE EXAMPLES:
 */

// --- DATABASE FIXTURE ---
export const testWithDB = test.extend({
  db: async ({}, use) => {
    // Connect to test database
    // const db = await connectToDatabase(process.env.TEST_DB_URL);

    // Optional: Seed database with test data
    // await db.seed('test-data.sql');

    // await use(db);

    // Cleanup: Truncate tables or rollback transaction
    // await db.cleanup();
    // await db.close();
  },
});

// --- MULTI-USER FIXTURE ---
export const testWithMultipleUsers = test.extend({
  user1Page: async ({ browser }, use) => {
    const context = await browser.newContext();
    const page = await context.newPage();
    // Login as user1
    await use(page);
    await context.close();
  },

  user2Page: async ({ browser }, use) => {
    const context = await browser.newContext();
    const page = await context.newPage();
    // Login as user2
    await use(page);
    await context.close();
  },
});

// --- MOCK API FIXTURE ---
export const testWithMockAPI = test.extend({
  mockAPI: async ({ page }, use) => {
    // Intercept API calls and return mock data
    await page.route('**/api/**', (route) => {
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          [mockDataField]: '[MOCK_VALUE]',
        }),
      });
    });

    await use(page);
  },
});

// --- FILE UPLOAD FIXTURE ---
export const testWithFileUpload = test.extend({
  testFile: async ({}, use) => {
    // Create temporary test file
    const fs = require('fs');
    const path = './test-uploads/test-file.txt';

    fs.writeFileSync(path, 'Test file content');

    await use(path);

    // Cleanup: Delete test file
    fs.unlinkSync(path);
  },
});

/**
 * USAGE EXAMPLES:
 *
 * Example 1: Using authenticated page fixture
 * ```typescript
 * import { test, expect } from './test-fixtures';
 *
 * test('User can access dashboard', async ({ authenticatedPage }) => {
 *   await authenticatedPage.goto('/dashboard');
 *   await expect(authenticatedPage.getByText('Welcome back')).toBeVisible();
 * });
 * ```
 *
 * Example 2: Using Page Object fixtures
 * ```typescript
 * test('Submit contact form', async ({ [pageObject1], testUser }) => {
 *   await [pageObject1].fillForm({
 *     email: testUser.email,
 *     name: testUser.name,
 *   });
 *   await [pageObject1].submitForm();
 *   expect(await [pageObject1].isSuccessMessageVisible()).toBe(true);
 * });
 * ```
 *
 * Example 3: Using API client fixture
 * ```typescript
 * test('Create order via API', async ({ apiClient }) => {
 *   const order = await apiClient.post('/orders', {
 *     productId: 'PROD-123',
 *     quantity: 2,
 *   });
 *   expect(order.status).toBe('pending');
 * });
 * ```
 *
 * Example 4: Combining multiple fixtures
 * ```typescript
 * test('Full checkout flow', async ({ [pageObject1], testUser, testProduct, apiClient }) => {
 *   // Setup: Create product via API
 *   await apiClient.post('/products', testProduct);
 *
 *   // Test: User adds product to cart and checks out
 *   await [pageObject1].addToCart(testProduct.id);
 *   await [pageObject1].checkout(testUser);
 *
 *   // Verify: Order created
 *   const orders = await apiClient.get(`/orders?user=${testUser.email}`);
 *   expect(orders).toHaveLength(1);
 * });
 * ```
 *
 * BEST PRACTICES:
 *
 * 1. Fixture Scope:
 *    - Use fixtures for reusable setup/teardown
 *    - Each fixture should have single responsibility
 *    - Clean up resources in teardown
 *
 * 2. Authentication:
 *    - Save authentication state to avoid repeated logins
 *    - Use storageState to persist cookies/tokens
 *    - Create separate fixtures for different user roles
 *
 * 3. Test Data:
 *    - Generate unique data per test (timestamps, UUIDs)
 *    - Clean up test data after tests
 *    - Use Faker.js for realistic test data
 *
 * 4. API Integration:
 *    - Use API for test setup (create users, products)
 *    - Faster than UI-based setup
 *    - More reliable for preconditions
 *
 * 5. Performance:
 *    - Avoid expensive setup in fixtures
 *    - Reuse authentication state
 *    - Use worker-scoped fixtures for shared resources
 *
 * 6. Maintainability:
 *    - Keep fixtures in separate file
 *    - Document fixture usage
 *    - Version control fixture data
 */
