"""Shared conversation per project — merge web + Slack history.

Revision ID: 006_shared_conversation
Revises: 005_slack_inbound
Create Date: 2026-04-07

Behaviour:
- Conversations.user_id becomes nullable.
- Old per-(project, user) unique constraint dropped.
- New partial unique index: one shared row per project where user_id IS NULL.
- Existing data migration: for each project, keep the most-recent conversation,
  rewrite its user_id to NULL, delete all others.
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "006_shared_conversation"
down_revision: Union[str, None] = "005_slack_inbound"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Make user_id nullable so we can insert shared rows
    op.alter_column("conversations", "user_id", existing_type=sa.dialects.postgresql.UUID(), nullable=True)

    # 2. Drop the old (project_id, user_id) unique constraint.
    #    The constraint name is autogenerated; in initial schema it was created
    #    via UniqueConstraint without a name → Postgres named it
    #    "conversations_project_id_user_id_key".
    op.execute("ALTER TABLE conversations DROP CONSTRAINT IF EXISTS conversations_project_id_user_id_key")

    # 3. Migrate data: for each project, keep the most recent conversation row,
    #    promote it to user_id = NULL, delete all other rows for that project.
    op.execute("""
        WITH ranked AS (
            SELECT id, project_id,
                   ROW_NUMBER() OVER (PARTITION BY project_id ORDER BY created_at DESC NULLS LAST) AS rn
            FROM conversations
        ),
        winners AS (
            SELECT id FROM ranked WHERE rn = 1
        )
        DELETE FROM conversations WHERE id NOT IN (SELECT id FROM winners);
    """)
    op.execute("UPDATE conversations SET user_id = NULL")

    # 4. Add a partial unique index to enforce one shared row per project.
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_conversations_shared_project "
        "ON conversations (project_id) WHERE user_id IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS uq_conversations_shared_project")
    # Cannot recreate the original (project_id, user_id) unique cleanly
    # because user_id is now NULL on every row. Best-effort: re-create the
    # constraint and let any conflict surface during the downgrade.
    op.alter_column("conversations", "user_id", existing_type=sa.dialects.postgresql.UUID(), nullable=False)
    op.create_unique_constraint(
        "conversations_project_id_user_id_key",
        "conversations",
        ["project_id", "user_id"],
    )
