"""Add output_kind to reminders — classifies what the reminder produces.

Revision ID: 023_reminder_output_kind
Revises: 022_reminder_recurrence
Create Date: 2026-04-21

Separates 'reminder fires' from 'what the agent spawns.' Before this,
every reminder with a BR/gap/person kicked off a full meeting-prep
agent run (~1min, LLM cost). Most PM reminders don't want that — they
want either a simple ping, or a short status summary, or (only for
real meetings) a full agenda.

Values:
  notification — chat/channel ping only, no file output (default)
  status       — short DB-backed summary of the BR/gap (no LLM)
  agenda       — full discovery-prep-agent meeting brief (historical behavior)
  research     — future: research-agent output
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "023_reminder_output_kind"
down_revision: Union[str, None] = "022_reminder_recurrence"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "reminders",
        sa.Column("output_kind", sa.String(), nullable=False, server_default="notification"),
    )
    # Backfill existing rows: if a row already has a prep_output_path,
    # it was generated by the old pipeline and IS an agenda. Everything
    # else was a plain ping.
    op.execute(
        "UPDATE reminders SET output_kind = 'agenda' "
        "WHERE prep_output_path IS NOT NULL"
    )


def downgrade() -> None:
    op.drop_column("reminders", "output_kind")
